<a href="https://colab.research.google.com/github/trupti2021/FirstGIT/blob/main/NNCreditCardFraudulent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install tensorflow

Assignment 1
Gen-AI Developers
Bronze Badge
This assignment consists of total 4 problems of ML and 1 project for LLM+RAG. Please do all the assignments as your own, don’t copy it from GPT. There will be a presentation one to one for the project or assignment also.
Problem Statement
A company wants to predict employee productivity scores to improve workforce planning and training programs. You are hired as a Data Scientist to build a multivariate linear regression model that predicts an employee’s Productivity Score based on multiple work-related factors.
Experience (yrs),Training Hours,Working Hours,Projects,Productivity Score
2,40,38,3,62
5,60,42,6,78
1,20,35,2,55
8,80,45,8,88
4,50,40,5,72
10,90,48,9,92
3,30,37,4,65
6,70,44,7,82
7,75,46,7,85
2,25,36,3,60
Interpretation
Which factor most strongly impacts productivity?
How does training affect productivity?
Should the company increase training hours or working hours?
What happens if Working Hours increase beyond optimal limits?
Can productivity ever decrease with more experience?
How would you detect overfitting in this model?
Suggest one new feature to improve prediction accuracy.

Problem Statement

A financial institution wants to predict whether a customer will default on a loan before approving it. Early identification of risky customers helps reduce financial loss.
You are working as a Machine Learning Analyst and must build a classification model using the K-Nearest Neighbors (KNN) algorithm to predict loan default.
This case introduces:
Mixed feature types
Financial risk interpretation
Class imbalance awareness
Age,AnnualIncome(lakhs),CreditScore(300-900), LoanAmount(lakhs), LoanTerm(years), EmploymentType, loan(yes/no)
28,6.5,720,5,5,Salaried,0
45,12,680,10,10,Self-Employed,1
35,8,750,6,7,Salaried,0
50,15,640,12,15,Self-Employed,1
30,7,710,5,5,Salaried,0
42,10,660,9,10,Salaried,1
26,5.5,730,4,4,Salaried,0
48,14,650,11,12,Self-Employed,1
38,9,700,7,8,Salaried,0
55,16,620,13,15,Self-Employed,1

Interpretation
Identify high-risk customers.
What patterns lead to loan default?
How do credit score and income influence predictions?
Suggest banking policies based on model output.
Compare KNN with Decision Trees for this problem.
What happens if LoanAmount dominates distance calculation?
Should KNN be used in real-time loan approval systems?

Problem Statement

Write a Python program to draw (visualize) the architecture of a Neural Network used to classify fraudulent and non-fraudulent credit card transactions.

Assume the fraud detection dataset contains the following input features:

TransactionAmount
TransactionTime
MerchantCategory
CustomerAge
AccountBalance
NumberOfTransactionsToday
Fraud (0 = Genuine, 1 = Fraud)

Problem Statement

Write a Python program to draw a 3D plot that visualizes the regression model for house price prediction using suitable Python-based 3D plotting libraries.

Assume the following features were used:
Area (sq ft)
Number of Bedrooms
House Price




Problem 5- PROJECT + Presentation

This is the case; you must develop using LLM and RAG. After submission you people must present to some of the panel members.


Use case: “Policy & Claims Copilot” (Customer support + Claims pre-check)
Goal - Help customers, agents, and claims teams get instant, consistent answers about:
what’s covered / not covered
limits & sub-limits
waiting periods
claim submission steps + timelines
documents needed
…and also do a pre-check of a claim scenario before submission.
This reduces call center load, speeds claim filing, and improves first-time-right submissions.

Why RAG is needed (vs plain LLM)
A plain LLM might “guess” policy terms. With RAG, the assistant:
retrieves the exact relevant clauses from the policy PDF
answers using only those clauses
quotes/links the source section/page (grounded response)

there is a pdf also

which i want to share

it is uploading

if that is not loaded please download from this link

https://content.sbigeneral.in/uploads/a370272f732749999e7c19e82e38ad7c.pdf




In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd

In [5]:
df=pd.read_csv("/content/drive/MyDrive/AutogluonDrop/fraud_sample.csv")

In [6]:
print(df.head())
print(df['FRAUD'].value_counts())

   Transaction_Amount  Transaction_Time Merchant_Category  Customer_Age  \
0             1872.34                14           Grocery            45   
1             4321.10                 2            Online            29   
2              120.55                10              Fuel            52   
3             3050.75                 1            Online            34   
4               89.99                18        Restaurant            41   

   Account_Balance  Transactions_Today  FRAUD  
0         45231.12                   3      0  
1         12000.50                  15      1  
2         78000.00                   2      0  
3         15000.00                  12      1  
4         64000.25                   1      0  
FRAUD
0    11
1     9
Name: count, dtype: int64


In [7]:
df

,Transaction_Amount,Transaction_Time,Merchant_Category,Customer_Age,Account_Balance,Transactions_Today,FRAUD
0,1872.34,14,Grocery,45,45231.12,3,0
1,4321.10,2,Online,29,12000.50,15,1
2,120.55,10,Fuel,52,78000.00,2,0
3,3050.75,1,Online,34,15000.00,12,1
4,89.99,18,Restaurant,41,64000.25,1,0
5,560.20,20,Grocery,38,72000.10,4,0
6,2750.00,3,Travel,30,18000.00,11,1
7,45.60,12,Fuel,55,82000.00,2,0
8,3999.99,23,Online,27,10000.00,14,1
9,150.00,9,Restaurant,48,50000.00,3,0


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Transaction_Amount  20 non-null     float64
 1   Transaction_Time    20 non-null     int64  
 2   Merchant_Category   20 non-null     object 
 3   Customer_Age        20 non-null     int64  
 4   Account_Balance     20 non-null     float64
 5   Transactions_Today  20 non-null     int64  
 6   FRAUD               20 non-null     int64  
dtypes: float64(2), int64(4), object(1)
memory usage: 1.2+ KB


In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.FRAUD.value_counts()

,count
FRAUD,
0,11
1,9


In [11]:
df=pd.get_dummies(df,columns=['Merchant_Category'],drop_first=True)

In [12]:
df

,Transaction_Amount,Transaction_Time,Customer_Age,Account_Balance,Transactions_Today,FRAUD,Merchant_Category_Grocery,Merchant_Category_Online,Merchant_Category_Restaurant,Merchant_Category_Travel
0,1872.34,14,45,45231.12,3,0,True,False,False,False
1,4321.10,2,29,12000.50,15,1,False,True,False,False
2,120.55,10,52,78000.00,2,0,False,False,False,False
3,3050.75,1,34,15000.00,12,1,False,True,False,False
4,89.99,18,41,64000.25,1,0,False,False,True,False
5,560.20,20,38,72000.10,4,0,True,False,False,False
6,2750.00,3,30,18000.00,11,1,False,False,False,True
7,45.60,12,55,82000.00,2,0,False,False,False,False
8,3999.99,23,27,10000.00,14,1,False,True,False,False
9,150.00,9,48,50000.00,3,0,False,False,True,False


In [13]:
X=df.drop('FRAUD',axis=1)
y=df['FRAUD']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape
#

((16, 9), (4, 9))

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
X_train

array([[ 1.53125645,  1.53660633, -1.41864978, -1.26022513,  1.47178399,
        -0.48038446,  1.73205081, -0.37796447, -0.48038446],
       [-0.65768616,  1.13791928, -0.34705166,  0.85150562, -0.52385532,
         2.081666  , -0.57735027, -0.37796447, -0.48038446],
       [-0.96628864,  0.60633655,  1.79614457,  1.46458435, -0.92298318,
         2.081666  , -0.57735027, -0.37796447, -0.48038446],
       [ 0.92719868, -1.38709869, -0.7367237 , -1.08992454,  1.07265613,
        -0.48038446,  1.73205081, -0.37796447, -0.48038446],
       [-0.95372055,  0.2076495 ,  1.60130855,  1.39646411, -1.12254711,
        -0.48038446, -0.57735027, -0.37796447, -0.48038446],
       [ 0.16356743,  1.0050236 ,  0.43229242,  0.03405937, -0.32429139,
         2.081666  , -0.57735027, -0.37796447, -0.48038446],
       [-0.81639419, -0.05814186,  0.04262038,  0.68120162, -0.72341925,
        -0.48038446, -0.57735027, -0.37796447, -0.48038446],
       [-0.93746156, -0.19103754,  1.01680048,  1.05586293, -0

In [16]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [17]:
model= Sequential()
model.add(Dense(3,activation='sigmoid',input_dim=X_train.shape[1]))
model.add(Dense(1,activation='sigmoid'))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [20]:
model.fit(X_train,y_train,epochs=30,validation_data=(X_test,y_test))

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5625 - loss: 0.7137 - val_accuracy: 0.5000 - val_loss: 0.7023
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5625 - loss: 0.7129 - val_accuracy: 0.5000 - val_loss: 0.7012
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5625 - loss: 0.7122 - val_accuracy: 0.5000 - val_loss: 0.7000
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5625 - loss: 0.7114 - val_accuracy: 0.5000 - val_loss: 0.6989
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5625 - loss: 0.7106 - val_accuracy: 0.5000 - val_loss: 0.6978
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5625 - loss: 0.7099 - val_accuracy: 0.5000 - val_loss: 0.6967
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5625 - loss: 0.7091 - val_accuracy: 0.5000 - val_loss: 0.6957
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.5625 - loss: 0.7084 - val_accuracy: 0.5000 - val_loss: 0.6946


In [21]:
model.layers[0].get_weights()
#

[array([[-0.2291232 ,  0.55306107,  0.57125497],
        [ 0.30102727, -0.23044959,  0.04979974],
        [-0.37734905, -0.63512516,  0.44823563],
        [ 0.4698363 , -0.21056016,  0.58021647],
        [ 0.67041   , -0.6523553 ,  0.05657388],
        [ 0.5936178 , -0.5064408 , -0.5092796 ],
        [-0.09188769,  0.0826384 ,  0.6606238 ],
        [ 0.6092606 ,  0.06134956, -0.1243303 ],
        [ 0.6366229 , -0.1535529 ,  0.70091313]], dtype=float32),
 array([0.03074421, 0.02977289, 0.01813694], dtype=float32)]

In [22]:
model.layers[0].get_weights()[0]

array([[-0.2291232 ,  0.55306107,  0.57125497],
       [ 0.30102727, -0.23044959,  0.04979974],
       [-0.37734905, -0.63512516,  0.44823563],
       [ 0.4698363 , -0.21056016,  0.58021647],
       [ 0.67041   , -0.6523553 ,  0.05657388],
       [ 0.5936178 , -0.5064408 , -0.5092796 ],
       [-0.09188769,  0.0826384 ,  0.6606238 ],
       [ 0.6092606 ,  0.06134956, -0.1243303 ],
       [ 0.6366229 , -0.1535529 ,  0.70091313]], dtype=float32)

In [26]:
y_pred=model.predict(X_test)
y_out=y_pred>0.5,1,0
y_out

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


(array([[False],
        [False],
        [False],
        [False]]),
 1,
 0)

In [29]:
import numpy as np
y_pred=model.predict(X_test)
y_out=np.where(y_pred>0.5,1,0)
y_out

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[0],
       [0],
       [0],
       [0]])